// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(ServerContext))]
    partial class ServerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.CuisineType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CuisineTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Afghani"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Pakistani"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Indian"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Labanese"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Thai"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Indonesian"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Mexican"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Chinese"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Korean"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Italian"
                        });
                });

            modelBuilder.Entity("backend.Models.HalalStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("HalalStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Status = "Certified Halal"
                        },
                        new
                        {
                            Id = 2,
                            Status = "Partially Halal"
                        },
                        new
                        {
                            Id = 3,
                            Status = "Vegeterian"
                        });
                });

            modelBuilder.Entity("backend.Models.Restaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CuisineTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("HalalStatusId")
                        .HasColumnType("integer");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Lat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Lng")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RestaurantTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Suburb")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("City");

                    b.HasIndex("Country");

                    b.HasIndex("CuisineTypeId");

                    b.HasIndex("HalalStatusId");

                    b.HasIndex("Lat");

                    b.HasIndex("Lng");

                    b.HasIndex("RestaurantTypeId");

                    b.HasIndex("State");

                    b.ToTable("Restaurants");
                });

            modelBuilder.Entity("backend.Models.RestaurantType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RestaurantTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Fast Food"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Casual Dinning"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Fine Dinning"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Take Away"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Food Truck"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Cafe"
                        });
                });

            modelBuilder.Entity("backend.Models.Restaurant", b =>
                {
                    b.HasOne("backend.Models.CuisineType", "CuisineType")
                        .WithMany()
                        .HasForeignKey("CuisineTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.HalalStatus", "HalalStatus")
                        .WithMany()
                        .HasForeignKey("HalalStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.RestaurantType", "RestaurantType")
                        .WithMany()
                        .HasForeignKey("RestaurantTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CuisineType");

                    b.Navigation("HalalStatus");

                    b.Navigation("RestaurantType");
                });
#pragma warning restore 612, 618
        }
    }
}
